substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: laundry_room_lights
  friendly_name: Laundry Room Lights
  ip_address: !secret laundry_room_lights_ip
  icon: "mdi:ceiling-light"

esphome:
  # https://esphome.io/components/esphome
  name: $device_name
  platform: ESP8266
  board: esp_wroom_02  # 2MB Flash


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $ip_address
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1
    dns2: !secret wifi_dns2


# web_server:
#   port: 80
  # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  # password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


# https://esphome.io/devices/sonoff_basic.html
# https://esphome.io/devices/sonoff.html#shelly-1


binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin: GPIO5
    name: $friendly_name Switch
    id: external_switch
    ## latching switch  e.g. light switch, Heltec/HTTM capacitive button
    on_press:
      - switch.toggle: relay_template
    on_release:
      - switch.toggle: relay_template
    internal: True

switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio.html
    pin: GPIO4
    id: relay
    icon: $icon

  # tie the binary_sensor & switch together and report status based on the relay state
  - platform: template
    # https://esphome.io/components/switch/template.html
    name: $friendly_name
    id: relay_template
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.toggle: relay
    turn_off_action:
      - switch.toggle: relay
    # optimistic: true # change the toggle switch in HA to individual on/off buttons
